### ISSUE TITLE
Found a 'fork' that I'm not sure about.

### ISSUE THREAD

**Issue by brisingraerowing** [McJtyMods/RFToolsPower#100]
[Is this acceptable?](https://www.curseforge.com/minecraft/mc-mods/rf-tools-power/files/4763946)

They also have it listed for numerous versions that it likely *isn't* compatible with.

EDIT: This is actually malware. Recommend reporting.

https://www.reddit.com/r/feedthebeast/comments/16t1far/psa_curseforge_user_mkatmonster_is_uploading/

**Comment by McJty** [comment]
Interesting, I actually reported it

**Comment by McJty** [comment]
CF removed the page. Thanks for letting me know
