### ISSUE TITLE
Crash when unloading chunk with Information Screen

### ISSUE THREAD

**Issue by ZXQWAS** [McJtyMods/RFToolsPower#17]
Another crash with information screen. I flew away and it crashed.
[crash-2018-09-30_17.38.23-server.txt](https://github.com/McJtyMods/RFToolsPower/files/2431655/crash-2018-09-30_17.38.23-server.txt)

**Comment by omglolbah** [comment]
Experiencing the same crash unfortunately. Consistently by placing an information screen and switching dimensions. Crash within a few minutes of doing so.

[crash-2019-05-18_18.04.28-server.txt](https://github.com/McJtyMods/RFToolsPower/files/3194258/crash-2019-05-18_18.04.28-server.txt)

**Comment by McJty** [comment]
This bug is already fixed in a later version
