### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by Darkosto** [McJtyMods/RFToolsPower#18]
Hey McJty! 

I've had this crash a couple times now. It doesn't seem to be easily replicated and does not happen every single load. But, I still wanted to share it with you just incase you were able to find the crash.

https://pastebin.com/tCB4ijsa

RFtools Power: 1.1.2
MC: 1.12.2
Forge: 2823

Thanks!
Darkosto

**Comment by McJty** [comment]
Hmm weird... That shouldn't be possible. I'll check it out

**Comment by McJty** [comment]
Not sure why it happens but in the next version I have addes some protection against this crash. Not sure when I'll release though as I'm in the middle of huge changes that affect all my mods and so I have to release all my mods at once
