### ISSUE TITLE
Server error when injecting @SidedProxy

### ISSUE THREAD

**Issue by AzPure** [McJtyMods/RFToolsPower#19]
Threw this into log on Aternos server. Unknown how to fix. Removing for compatibility issues. 
`

[23:12:59] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
--
1190 | java.lang.NoClassDefFoundError: Lmcjty/rftoolspower/proxy/CommonProxy;
1191 | at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_202]
1192 | at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_202]
1193 | at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_202]
1194 | at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:70) ~[forge.jar:?]
1195 | at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611) ~[forge.jar:?]
1196 | at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
1197 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
1198 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
1199 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1200 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1201 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1202 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1203 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1204 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1205 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1206 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge.jar:?]
1207 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge.jar:?]
1208 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
1209 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
1210 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
1211 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
1212 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1213 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1214 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1215 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1216 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1217 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1218 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1219 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
1220 | at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593) ~[Loader.class:?]
1221 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
1222 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
1223 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
1224 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
1225 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
1226 | Caused by: java.lang.ClassNotFoundException: mcjty.rftoolspower.proxy.CommonProxy
1227 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
1228 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
1229 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
1230 | ... 35 more
1231 | Caused by: java.lang.NoClassDefFoundError: mcjty/lib/proxy/AbstractCommonProxy
1232 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_202]
1233 | at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_202]
1234 | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_202]
1235 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
1236 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
1237 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
1238 | ... 35 more
1239 | Caused by: java.lang.ClassNotFoundException: mcjty.lib.proxy.AbstractCommonProxy
1240 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
1241 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
1242 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
1243 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_202]
1244 | at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_202]
1245 | at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_202]
1246 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
1247 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
1248 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
1249 | ... 35 more
1250 | [23:12:59] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /aternos/server/./crash-reports/crash-2019-05-05_23.12.59-server.txt

`

**Comment by McJty** [comment]
Versions?

**Comment by McJty** [comment]
The reason I ask is that it appears you're not using the latest version of one of my mods
