### ISSUE TITLE
Add modded wrench support

### ISSUE THREAD

**Issue by AssB0ys** [McJtyMods/RFToolsPower#20]
Hello. I want to use this mod in my minecraft world, the only other technical mod that I use is Industrial Foregoing and there seem to be no way to transfer the energy between these two mods. I noticed that the TeslaCoreLib wrench doesn't work with RfToolsPower batteries. It would be nice to add support for wrenches from other mod or at least provide the wrench with this mod. Thank you.

**Comment by McJty** [comment]
I no longer work on 1.12 and in 1.15 this problem is no longer present
