### ISSUE TITLE
[1.14.4] Players kicked when placing an Information screen on a dedicated server - Can't serialize unregistered packet

### ISSUE THREAD

**Issue by ProsperCraft** [McJtyMods/RFToolsPower#23]
rftoolspower-1.14-1.2.2-alpha.jar
Forge 28.0.40

https://gist.github.com/ProsperCraft/110d11cf531875099566bdc6cfa76498

We removed the blocks with worldedit, then reproduced it again.

Place down a coal furnace, then a tier 1 powercell next to it then put an information panel on it, and bam.

Must be on a dedicated server, I could not make it happen in single player.

Client logs-

[logs.zip](https://github.com/McJtyMods/RFToolsPower/files/3473945/logs.zip)

**Comment by 2iguys** [comment]
this issue happens for us to, so I can confirm.

**Comment by Rakambda** [comment]
Same here

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed in latest version
