### ISSUE TITLE
[1.14.4] Coal generator and other recepies are not longer working.

### ISSUE THREAD

**Issue by ProsperCraft** [McJtyMods/RFToolsPower#24]
The only recipes that work now are - power cell medium, high, power core low

rftoolspower-1.14-1.2.3-alpha
forge-1.14.4-28.0.45

**Comment by ProsperCraft** [comment]
One of my players says the texture is broken in JEI as well for the coal gen.

**Comment by McJty** [comment]
I cannot reproduce this. Can you show me the log?

**Comment by ProsperCraft** [comment]
We figured it out, RFtools base is not download when you download rftools power, RFtools base is marked as an alpha which doesn't sync across curse networks and wont show up in the Twitch launcher as a download, 

Solution, mark RFtools base as a mod that is downloaded when rftools power is downloaded and mark rftools base as a beta so it can sync.

**Comment by McJty** [comment]
I updated it to beta stage. Does this solve the issue?

**Comment by ProsperCraft** [comment]
Yes, I can verify that deleting rfpower and readding it, the base comes with it now.

I have not tried the recipe yet, because I can't get my single player instance to load(still trying to find what mod is causing this) but I suspect it works, if not I will come back.
