### ISSUE TITLE
[1.14.4] Coal generator missing textures

### ISSUE THREAD

**Issue by ScrambledGamer** [McJtyMods/RFToolsPower#25]
Coal generator missing texture on all sides besides front when not active and front also missing when active

**Comment by McJty** [comment]
More information please! Versions of the mod, forge, ...

**Comment by ProsperCraft** [comment]
Duplicate of - https://github.com/McJtyMods/RFToolsPower/issues/24

**Comment by McJty** [comment]
Can't reproduce

**Comment by ProsperCraft** [comment]
I resolved this in https://github.com/McJtyMods/RFToolsPower/issues/24 you can close.
