### ISSUE TITLE
[1.14.4] Client crash on load with forge 1.14.4-28.1.6

### ISSUE THREAD

**Issue by ProsperCraft** [McJtyMods/RFToolsPower#26]
Crash log- 
https://gist.github.com/ProsperCraft/1c66c33d5aa6eaa0743c7b44cb137e77

Forge-
1.14.4-28.1.6

rftoolsbase-1.14-0.0.3-alpha
rftoolspower-1.14-1.2.3-alpha

Modpack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk
as yet unreleased update to Forge 28.1.6

**Comment by McJty** [comment]
My mods need updating to latest Forge. I'm still working on that

**Comment by andr9528** [comment]
I'm using the exact same mentioned versions, and i'm not crashing, i'm in single player if that has any say as to why i'm not crashing.

**Comment by ProsperCraft** [comment]
New crash with forge 28.1.22
https://gist.github.com/ProsperCraft/b71507308a188af6ea4cbcc81ead419b
Pack
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by ProsperCraft** [comment]
[latest.log](https://github.com/McJtyMods/RFToolsPower/files/3658977/latest.log)

**Comment by McJty** [comment]
I have no idea how this can break. Maybe some other mod in your pack is messing things up

**Comment by ProsperCraft** [comment]
Yea, more of current forges 1.14.4 let things break and show the wrong stacktrace crashes, I will investigate.
