### ISSUE TITLE
[1.14.4] Inverted Buttons in GUI

### ISSUE THREAD

**Issue by andr9528** [McJtyMods/RFToolsPower#27]
The buttons that is hovered are simply inverted, nothing big, just thought i would mention it.
Though i did expect stuff to happen when clicking the buttons, but nope.

![capture_001_18092019_201208](https://user-images.githubusercontent.com/21788044/65174305-f25e0e80-da50-11e9-8c34-d1f1009ea922.jpg)

![capture_002_18092019_201240](https://user-images.githubusercontent.com/21788044/65174308-f25e0e80-da50-11e9-9321-dc15d0fd5378.jpg)

Images are taken in the coal generator, don't know if it is only this one that is effected.

Versions:
Minecraft: 1.14.4
Forge: 28.1.6
RFTools Base: 0.0.3-alpha.
RFTool Power: 1.2.3-alpha

**Comment by McJty** [comment]
Fixed in latest version
