### ISSUE TITLE
[1.14.4] Client crashes when booting on Forge ver: 28.1.39

### ISSUE THREAD

**Issue by Gbergz** [McJtyMods/RFToolsPower#28]
Title^ Game crashes when booting, Forge 28.1.20 works fine.

MC: 1.14.4
Forge: 28.1.39
Mod-Version: 1.2.4-alpha

Crash-Log: [GistGithub](https://gist.github.com/Gbergz/4442ed720f3b801d82945468b2f4d5ae)

**Comment by McJty** [comment]
This has been reported before but I cannot reproduce it and I have no clue what could cause this

**Comment by McJty** [comment]
This is a bug in forge
