### ISSUE TITLE
Are translations wanted?

### ISSUE THREAD

**Issue by Aresiel** [McJtyMods/RFToolsPower#29]

**Comment by McJty** [comment]
yes but maybe only after the mod is more final. i.e. not all blocks have been added yet

**Comment by Aresiel** [comment]
Ok, wondering since I've seen a few PRs about it but no accepted ones. Close?

**Comment by McJty** [comment]
That's just me being very bad with accepting PR's :-)

**Comment by Aresiel** [comment]
Ah lol. Anything more to say? Else I'll close.
