### ISSUE TITLE
1.14 Powercells do not keep power when broken.

### ISSUE THREAD

**Issue by Darkere** [McJtyMods/RFToolsPower#30]
Not sure if just not yet done or just not working correctly. 

Breaking a powercell voids all energy inside them.

**Comment by McJty** [comment]
Powercells or dimensional cells?

**Comment by Darkere** [comment]
both

**Comment by McJty** [comment]
Um that's weird. That did work fine for me. You're in survival I assume?

**Comment by McJty** [comment]
And what version btw?

**Comment by Darkere** [comment]
rftoolspower-1.14-1.2.6-alpha

let me check if its only on servers

**Comment by Darkere** [comment]
and yes survival

**Comment by Darkere** [comment]
Also happens in Singleplayer. Neither does the input output configuration change.

**Comment by McJty** [comment]
Should be ok now
