### ISSUE TITLE
Crash on startup [1.14.4]

### ISSUE THREAD

**Issue by MelanX** [McJtyMods/RFToolsPower#32]
Forge: 28.1.70
RFTools Power: 1.2.6-alpha
Crash-log: https://pastebin.com/5d1LT7tE

Whether with or without OptiFine.
Do you need more information? Tell me, please :)

**Comment by McJty** [comment]
Bug in forge. Just startup again

**Comment by NielsPilgaard** [comment]
I'm having this issue as well, I've restarted 3 times without luck now. 

### Versions
- Forge 1.14.4-28.1.87
- mcjtylib-1.14-3.5.11-alpha
- rftoolspower-1.14-1.2.7-alpha

**Comment by McJty** [comment]
Can you give me your crashlog? I would like to see exactly where it crashes

**Comment by NielsPilgaard** [comment]
Oh woops, here you go: https://gist.github.com/NillerMedDild/75055c01d2a98cd53a6eff7598ed811d

**Comment by NielsPilgaard** [comment]
Oh lord, I see Twitch didn't *actually* update the mods I clicked update on. Sorry for the inconvinience, I can start the game just fine.

**Comment by McJty** [comment]
Ok good. For now I'll close this again

**Comment by Algorn120** [comment]
Getting the same crashes as above, figured I'd reopen this rather than start a new issue. 
Here's the crash log: https://pastebin.com/yW3LUzu2
On forge 28.1.90, V 1.14.4,
Also using the most recently updated mod file (Updated 21 hours ago as of this comment)
Let me know if you need more info!

**Comment by McJty** [comment]
Do you have McJtyLib?

**Comment by Algorn120** [comment]
... I am not a smart man. Nevermind LOL
