### ISSUE TITLE
dimension cells cannot be linked

### ISSUE THREAD

**Issue by daniel-for-github** [McJtyMods/RFToolsPower#33]
mc 1.14.4,forge-1.14.4-28.1.61
mcjtylib-1.14-3.5.11-alpha.jar,rftoolsbase-1.14-0.0.8-alpha.jar,rftoolspower-1.14-1.2.8-alpha.jar

the dimension cells are not sharing power, cannot be linked
No recipe for network card

regards

**Comment by McJty** [comment]
Ah I will fix that. That's a stupid oversight

**Comment by McJty** [comment]
Should be fixed now
