### ISSUE TITLE
[1.14.4] Coal Generator any items as fuel

### ISSUE THREAD

**Issue by Siriuo** [McJtyMods/RFToolsPower#34]
Any item can be inserted using a vanilla hopper which can then be used as fuel and generates power. 

Below screenshot of setup.

![Setup](https://puu.sh/EG8FM/02094fd19d.png)

![UI](https://puu.sh/EG8FO/bdba124d9d.png)

Versions:
Forge: 1.14.4 - 28.1.90
Lib: 1.14-3.5.12-alpha
Base: 1.14-0.0.9-alpha
Builder: 1.14-1.2.8-alpha
Power: 1.14-1.2.9-alpha
Storage: 1.14-0.0.4-alpha
Utility: 1.14-1.2.9-alpha

**Comment by McJty** [comment]
Will be fixed next release. Thanks for reporting
