### ISSUE TITLE
Rendering Block Entity crash after placing screen [1.14.2]

### ISSUE THREAD

**Issue by TheDarkPreacher** [McJtyMods/RFToolsPower#35]
Pack: FTB Unstable
Forge Version: 28.1.90
RFTools Mods: RFTools Base 0.0.11-alpha, RFTools Builder 1.2.10-alpha, RFTools Power 1.2.11-alpha, RFTools Utility 1.2.12, McJtyLib 3.5.15

Expected behavior: Place screen, be able to use it.
Actual behavior: Place screen, CTD.

Fixed issue by disabling all RFTools mods, loading up the world, then closing. Will look into Forge config, see if erroring tile entities config setting can be turned on.

Crash log attached.

[crash-2019-12-03_12.44.16-client.txt](https://github.com/McJtyMods/RFToolsPower/files/3918204/crash-2019-12-03_12.44.16-client.txt)

**Comment by TheDarkPreacher** [comment]
Updated to Forge 28.1.99
New development. Getting CTD just holding the Screen in hand now.
Crash log attached.
[crash-2019-12-03_13.27.40-client.txt](https://github.com/McJtyMods/RFToolsPower/files/3918348/crash-2019-12-03_13.27.40-client.txt)

**Comment by McJty** [comment]
Known bug in forge which will be fixed soon I hope. Workaround is to disable truetype fonts in the rftools utility client config
