### ISSUE TITLE
[1.14] Energy cells FE compatibility (pulling/extraction problem)

### ISSUE THREAD

**Issue by owmii** [McJtyMods/RFToolsPower#37]
Forge: 28.1.96
mcjtylib-1.14-3.5.16-alpha
rftoolsbase-1.14-0.0.12-alpha
rftoolspower-1.14-1.2.12-alpha

Energy cells `SidedHandler#canExtract` returns false even when set to out mode, so this make a compatibility problem when trying to pull energy, and that's what happen with my mod .

**Comment by McJty** [comment]
That's normal. FE/RF is a push model. It is not supposed to be possible to extract power out of a powercell. Instead the powercell will push power to adjacent blocks. You should not try to pull power out of something. That's not going to work for many generators/powercells and so on

**Comment by owmii** [comment]
Push model? this make a limited compatibility, or I am wrong? FE should work like it is. 
BDW , Thank you!

**Comment by McJty** [comment]
I feel it was a mistake to allow extracting of energy in the API. I never allow it on any of my blocks. For power cells for example it complicates bookkeeping as they are only supposed to emit a certain amount of FE per side every tick. That's easy for me to control when I simply push that amount to adjacent machines every tick (as I'm doing now) but if other machines would be able to extract then I would have to keep track of that so I know how much a machine is still allowed to extract every tick
