### ISSUE TITLE
PowerCell not rendering on load

### ISSUE THREAD

**Issue by IamStig** [McJtyMods/RFToolsPower#38]
Forge 28.1.107
Lib 3.5.17
Mod 1.2.12

When game loads, or player leaves and returns to dimension,  some of the Powercells do not render, the one probe says they are there but it is not only invisible solid blocks passed the cell are also "xrayed" through. 
I have about 12 cells connected together (my solution to no conduits earlier) and some render and some don't. There are 4 or 5 not rendering at the top, 2 on the side of those render and 5 at the bottom render. 
The cells can be restored, visually by a right click with empty hand.

Interestingly I have just noticed that a chest that is next to a couple of these cells is also invisible
![PowerCell](https://user-images.githubusercontent.com/20489424/71057796-02050480-21b2-11ea-8123-9b3d6544dff2.gif)

**Comment by McJty** [comment]
Anything special in the logs?

**Comment by IamStig** [comment]
No mate it is not crashing .... everything is fine except missing render. It might not be your mod, it was just that your cell was, I thought, the only thing effected ....but now I am seeing a chest at top is also not rendering and 2 in the same chunk but away from the cells are also invisible ...until clicking on them. It is not affecting the game at all ...but it is odd and unexplained

**Comment by McJty** [comment]
I know it's not crashing but I'd like to see the log anyway

**Comment by IamStig** [comment]
Sorry for delay, was Dinner and news time. This is the lattest log
http://www.mediafire.com/file/u47mruxkwr0gd2v/Latest_log.rar/file

**Comment by IamStig** [comment]
Hi McJty, hope Christmas was good to you. I have a small update. Still the only things going invisible are some of your PowerCells and a couple of vanilla chests .... all in the same chunk. Difference now after update to forge 28.1.109 is the blocks appear just by looking at them (as opposed to right clicking)
Doubt it helps much, I've still not a clue what is happening

**Comment by IamStig** [comment]
I am closing this as I am totally confused as to what is the cause & I have closed that test world.
Interestingly on the new map I am playing I have had a similar experience (invisible til you look at the space) .... only with vanilla chests and only in a Lost City so far
