### ISSUE TITLE
[Forge 1.14.4] Crash on load - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ScottoMotto** [McJtyMods/RFToolsPower#39]
Only RFTools mods. Forge 28-111.
java.lang.NoSuchMethodError: javax.vecmath.Vector4f.setW(F)V
https://pastebin.com/tbUWEmYh

All other RFTools modules work. Just RFTools Power crashes.

**Comment by McJty** [comment]
Seems to be a bug in forge to be honest. RFTools simply uses OBJ models and it is crashing in forge code while loading those

**Comment by ScottoMotto** [comment]
Posted to Forge forum:
https://www.minecraftforge.net/forum/topic/80090-1144-crash-on-load-with-rftools-power/
