### ISSUE TITLE
Crash searching through creative mode on 1.15.2

### ISSUE THREAD

**Issue by BedrockLegends** [McJtyMods/RFToolsPower#45]
https://gist.github.com/BedrockLegends/8b934341d0a3f1ae9bbb64599fb0ddb4

This happen after your latest update

**Comment by McJty** [comment]
But RFToolsPower wasn't even updated? What are your other mods that you have and which ones did you update?

**Comment by BedrockLegends** [comment]
@McJty its happening on my Monumental Experience modpack, https://www.curseforge.com/minecraft/modpacks/monumental-experience
