### ISSUE TITLE
Huges lags to freeze when a lot of powercell are connected together 1.12.2-1.2.0

### ISSUE THREAD

**Issue by Alexlion2308** [McJtyMods/RFToolsPower#47]
I crafted 125 high powercell to create a 5x5x5 multiblock powercell but it create huges lags in the game, Skipping ticks half the time, and less than 5 fps on the rest.

I let 20 and there is no longer lag (just normal pc lag but thats my config).
If i reconnect together again but in line it huge laging. 
If i place all 125 but not all together it not lagging (by 10-20 cube/cluster) 

I will use this last solution but if it can inprove the mod for futur updates.

Minecraft 1.12.2
Custom Modpack based on FTB Revelation
RFToolsPower 1.2.0
Forge 14.23.5.2846

**Comment by McJty** [comment]
Yes, this may be a bit too much for it. Unfortunatelly this is not going to be fixed as I no longer work on 1.12

**Comment by Alexlion2308** [comment]
Ok. I make 6 unit of 22 High powercell (25kRf I/O) and it works fine, i make also a linked advanced powercell and it works also fine crosse dimension (RIP Tesseract). RFTools Mods are greats mods thanks for it !
