### ISSUE TITLE
[1.16.2] Mod crashes on server side along side Xnet

### ISSUE THREAD

**Issue by BedrockLegends** [McJtyMods/RFToolsPower#53]
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	XNet (xnet) has failed to load correctly
§7java.lang.IllegalAccessError: no such method: mcjty.xnet.setup.ClientSetup.init(FMLClientSetupEvent)void/invokeStatic,
	RFToolsPower (rftoolspower) has failed to load correctly
§7Attempted to load class net/minecraft/client/renderer/model/ModelManager for invalid dist DEDICATED_SERVER,
	RFToolsUtility (rftoolsutility) has failed to load correctly
§7Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.2-33.0.20.jar:33.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.2-33.0.20.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.2-33.0.20.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.2-33.0.20.jar:?]

**Comment by McJty** [comment]
Versions please!

**Comment by BedrockLegends** [comment]
1.16-3.0.2 - xnet
1.16-3.0.3 Rftools Power
1.16-3.0.4 Rftools Utilitys

We have been having so much issues with your mods as of late not working on server in general

**Comment by McJty** [comment]
You may need to download XNet again. There was a problem earlier today with a corrupt XNet archive. Try that first

**Comment by BedrockLegends** [comment]
26.08 11:57:49 [Server] modloading-worker-27/ERROR [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: xnet, class mcjty.xnet.XNet
26.08 11:57:49 [Server] INFO java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such method: mcjty.xnet.setup.ClientSetup.init(FMLClientSetupEvent)void/invokeStatic
26.08 11:57:49 [Server] INFO at mcjty.xnet.XNet.<init>(XNet.java:34) ~[?:1.16-3.0.2-beta] {re:classloading}
26.08 11:57:49 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:33.0] {re:classloading}
26.08 11:57:49 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:33.0] {re:classloading}
26.08 11:57:49 [Server] INFO at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?] {re:classloading}
26.08 11:57:49 [Server] INFO at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?] {re:classloading}
26.08 11:57:49 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO Caused by: java.lang.IllegalAccessError: no such method: mcjty.xnet.setup.ClientSetup.init(FMLClientSetupEvent)void/invokeStatic
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO ... 20 more
26.08 11:57:49 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IBlockColor
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO ... 20 more
26.08 11:57:49 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.color.IBlockColor
26.08 11:57:49 [Server] INFO at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:104) ~[modlauncher-6.1.1.jar:?] {re:classloading}
26.08 11:57:49 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO ... 20 more
26.08 11:57:49 [Server] INFO Suppressed: java.lang.ClassNotFoundException
26.08 11:57:49 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:263) ~[modlauncher-6.1.1.jar:?] {}
26.08 11:57:49 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134) ~[modlauncher-6.1.1.jar:?] {re:classloading}
26.08 11:57:49 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-6.1.1.jar:?] {re:classloading}
26.08 11:57:49 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at mcjty.xnet.XNet.<init>(XNet.java:34) ~[?:1.16-3.0.2-beta] {re:classloading}
26.08 11:57:49 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_251] {}
26.08 11:57:49 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251] {}
26.08 11:57:50 [Multicraft] Skipped 119 lines due to rate limit (100/s)
26.08 11:57:50 [Server] modloading-worker-15/FATAL [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
26.08 11:57:50 [Server] modloading-worker-15/ERROR [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: rftoolsutility, class mcjty.rftoolsutility.RFToolsUtility
26.08 11:57:50 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.2-33.0.20.jar:33.0] {}
26.08 11:57:50 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:82) ~[modlauncher-6.1.1.jar:?] {}
26.08 11:57:50 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:118) ~[modlauncher-6.1.1.jar:?] {}
26.08 11:57:50 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247) ~[modlauncher-6.1.1.jar:?] {}
26.08 11:57:50 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134) ~[modlauncher-6.1.1.jar:?] {re:classloading}
26.08 11:57:50 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-6.1.1.jar:?] {re:classloading}
26.08 11:57:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:231) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:186) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:180) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:174) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at mcjty.rftoolsutility.RFToolsUtility.<init>(RFToolsUtility.java:36) ~[?:1.16-3.0.4] {re:classloading}
26.08 11:57:50 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) ~[?:33.0] {re:classloading}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:33.0] {re:classloading}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?] {re:classloading}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?] {re:classloading}
26.08 11:57:50 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_251] {}
26.08 11:57:50 [Server] modloading-worker-15/ERROR [ne.mi.fm.ja.FMLModContainer/LOADING]: An error occurred while dispatching event CONSTRUCT to rftoolsutility
26.08 11:57:50 [Server] modloading-worker-15/FATAL [ne.mi.ev.EventBus/EVENTBUS]: EventBus 49 shutting down - future events will not be posted.
26.08 11:57:50 [Server] INFO java.lang.Exception: stacktrace
26.08 11:57:50 [Server] INFO at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) ~[eventbus-3.0.3-service.jar:?] {}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) ~[?:33.0] {re:classloading}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) ~[?:33.0] {re:classloading}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) ~[?:?] {re:classloading}
26.08 11:57:50 [Server] INFO at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) ~[?:?] {re:classloading}
26.08 11:57:50 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_251] {}
26.08 11:57:50 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_251] {}
26.08 11:57:50 [Server] modloading-worker-23/ERROR No data fixer registered for appliedenergistics2:tiny_tnt_primed
26.08 11:57:50 [Server] modloading-worker-23/ERROR No data fixer registered for appliedenergistics2:singularity
26.08 11:57:50 [Server] modloading-worker-23/ERROR No data fixer registered for appliedenergistics2:charged_quartz
26.08 11:57:50 [Server] modloading-worker-23/ERROR No data fixer registered for appliedenergistics2:growing_crystal
26.08 11:57:50 [Server] main/INFO [ne.mi.fm.DeferredWorkQueue/LOADING]: Dispatching synchronous work after CONSTRUCT: 2 jobs
26.08 11:57:50 [Server] main/INFO [ne.mi.fm.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 00:00:00.010
26.08 11:57:50 [Server] main/FATAL [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 3 errors found
26.08 11:57:51 [Server] main/FATAL Failed to start the minecraft server
26.08 11:57:51 [Server] INFO net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
26.08 11:57:51 [Server] INFO XNet (xnet) has failed to load correctly
26.08 11:57:51 [Server] INFO §7java.lang.IllegalAccessError: no such method: mcjty.xnet.setup.ClientSetup.init(FMLClientSetupEvent)void/invokeStatic,
26.08 11:57:51 [Server] INFO RFToolsPower (rftoolspower) has failed to load correctly
26.08 11:57:51 [Server] INFO §7Attempted to load class net/minecraft/client/renderer/model/ModelManager for invalid dist DEDICATED_SERVER,
26.08 11:57:51 [Server] INFO RFToolsUtility (rftoolsutility) has failed to load correctly
26.08 11:57:51 [Server] INFO §7Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
26.08 11:57:51 [Server] INFO ]
26.08 11:57:51 [Server] INFO at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
26.08 11:57:51 [Server] INFO at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?] {re:classloading}
26.08 11:57:51 [Server] INFO at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49) ~[?:?] {re:classloading}
26.08 11:57:51 [Server] INFO at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
26.08 11:57:51 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
26.08 11:57:51 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251] {}
26.08 11:57:51 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251] {}
26.08 11:57:51 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251] {}
26.08 11:57:51 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.2-33.0.20.jar:33.0] {}
26.08 11:57:51 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
26.08 11:57:51 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
26.08 11:57:51 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
26.08 11:57:51 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
26.08 11:57:51 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}
26.08 11:57:51 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.2-33.0.20.jar:?] {}
26.08 11:57:51 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.2-33.0.20.jar:?] {}
26.08 11:57:51 [Server] INFO at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.2-33.0.20.jar:?] {}
26.08 11:57:51 [Multicraft] Server shut down (starting)
26.08 11:57:51 [Multicraft] Restarting crashed server in 2.0 seconds

**Comment by BedrockLegends** [comment]
Both Rftools Power and xnet

**Comment by McJty** [comment]
What version of forge?

**Comment by BedrockLegends** [comment]
1.16.2 - 33.0.21

**Comment by McJty** [comment]
I currently have no clue at all what's going on. I'll have to check this out later as I ran out of time

**Comment by BedrockLegends** [comment]
[crash-2020-08-26_12.11.17-client.txt](https://github.com/McJtyMods/RFToolsPower/files/5131318/crash-2020-08-26_12.11.17-client.txt)

Also rftoolsutility now crash on client well using the new forge version 33.0.22

**Comment by UnRealDinnerbone** [comment]
I did some testing it looks like the error is because of 
`FMLJavaModLoadingContext.get().getModEventBus().addListener(ClientSetup::init);
FMLJavaModLoadingContext.get().getModEventBus().addListener(ClientSetup::modelInit);`
In Xnet constructor, to fix I belive you need to do is run those inside of a DistExecutor

**Comment by McJty** [comment]
Can you test again? All my mods have updated (McJtyLib, RFToolsBase, XNet, ...) so you'll have to update all of them. Thanks

**Comment by BedrockLegends** [comment]
@McJty It works now on the new versions
