### ISSUE TITLE
[1.16.2] powercell card uses its registry name

### ISSUE THREAD

**Issue by WhitePhant0m** [McJtyMods/RFToolsPower#54]
![image](https://user-images.githubusercontent.com/33400200/92378150-055c6980-f10e-11ea-8267-fcc9ead353f1.png)

**Comment by McJty** [comment]
Hmm that's weird. Works correct for me. What version do you have?

**Comment by WhitePhant0m** [comment]
nvm, seems like I was using an older version, I though I had updated to latest release.
