### ISSUE TITLE
Server crash 1.16.3

### ISSUE THREAD

**Issue by BedrockLegends** [McJtyMods/RFToolsPower#57]
[crash-2020-10-02_01.23.28-server.txt](https://github.com/McJtyMods/RFToolsPower/files/5316276/crash-2020-10-02_01.23.28-server.txt)

**Comment by McJty** [comment]
Update McJtyLib

**Comment by BedrockLegends** [comment]
Your MCJTLIB causes crashes with other mods like I stated before

**Comment by McJty** [comment]
And as I also said this is not the fault of mcjtylib
