### ISSUE TITLE
1.16.5 - Crash since updating

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [McJtyMods/RFToolsPower#70]
![uN2MYa9 1](https://user-images.githubusercontent.com/10351221/124827286-7beb1300-df3b-11eb-9151-d33b06d671ee.png)

**Comment by viridior** [comment]
No issue when reverting back to mcjtylib-1.16-5.0.19.jar, seems to work with rftoolsutility-1.16-3.1.0.jar and rftoolspower-1.16-3.0.9.jar as well.

**Comment by P3rf3ctXZer0** [comment]
I will give it a shot.

**Comment by BedrockLegends** [comment]
its McjtyLib causing the crash

**Comment by P3rf3ctXZer0** [comment]
Indeed.

**Comment by McJty** [comment]
Can you try the new McJtyLib once CurseForge approves?

**Comment by P3rf3ctXZer0** [comment]
Its fixed
