### ISSUE TITLE
Breaking a Power Level causing a crash (1.18.1)

### ISSUE THREAD

**Issue by enigmaquip** [McJtyMods/RFToolsPower#77]
Placing down a power level block and then breaking it with either a pickaxe or sneak right clicking with a wrench causes an instant crash. (Tested in forge versions 39.0.10 and 39.0.19)

Forge 39.0.10
mcjtylib-1.18-6.0.6
rftoolsbase-1.18-3.0.3
rftoolsutility-1.18-4.0.5
rftoolspower-1.18-4.0.2
rftoolsbuilder-1.18-4.0.4
rftoolsstorage-1.18-3.0.4
xnet-1.18-4.0.3                  

[Crash Log](https://pastebin.com/jWJEz7Q0)

**Comment by McJty** [comment]
Fixed in 1.16 and 1.18
