### ISSUE TITLE
endergenic generator ui 1.18.1

### ISSUE THREAD

**Issue by LoneWolf137** [McJtyMods/RFToolsPower#80]
the ui of the endergenic generator does not render when looking at it.
mod version 4.0.3

![2022-02-03_01 51 40](https://user-images.githubusercontent.com/42692808/152262867-0bfc22d0-f973-447d-af84-bec37828bfc6.png)
![2022-02-03_01 51 47](https://user-images.githubusercontent.com/42692808/152262899-33e56cb1-edaa-4681-9dfa-01798b2e30fa.png)

**Comment by sarim** [comment]
#58

**Comment by WildstyleTrinity** [comment]
I have seen the other article. OneProbe is showing some information, but without the pearl rendering in the generators a configuration only with OneProbe is almost impossible. Is there a plan to fix the pearl rendering and Tool UI for 1.18 ?

**Comment by MCChiter** [comment]
Somehow i didn't find this issue when searching but yes, oneprobe is a good mob but squatting and spinning around hoping to hit the exact moment the pearls fails in one of the endergenics that even when sequenced proper manage to somehow work different and say in Probe "Pearl arrived at 10" and "pearl arrived while idle" at the same time is far from helpful when setting up a loop system intended to run around 2 times a second with information presented to you only in 5s intervals and no way to get MORE DATA

**Comment by Kangy1103** [comment]
I'm also seeing this (or not seeing as the case may be) on 1.18.2 on rftoolspower-1.18-4.0.7. Happy to open my own bug report if needed. Just let me know :)

**Comment by McJty** [comment]
Fixed
