### ISSUE TITLE
Power Monitor has trouble with later game Mekanism storage

### ISSUE THREAD

**Issue by CantBeLucifer** [McJtyMods/RFToolsPower#82]
Power Monitor seems to store the power level as a Integer this is a bit of an issue as Mekanism late game power storage stores billions of RF in a mutliblock structure. As far as I can tell it seems that in a multiblock structure the power monitor detects 2147483647 RF as 100% despite the total capacity being 3 trillion RF.

Probably could do with switching the stored power level to a long instead of an int, as it's quite easy to end up with more than 2 billion RF.

**Comment by McJty** [comment]
Not a bug. The forge energy API only supports 32 bit so I have no way to read those larger numbers
