### ISSUE TITLE
[1.19.*] Power Cells not Saving Energy Level

### ISSUE THREAD

**Issue by HalcyonSeas73** [McJtyMods/RFToolsPower#88]
Minecraft version: 1.19+, tested on 1.19.2
Forge version: 43.0.8
McJtyLib version: 7.0.2
RFToolsBase version: 4.0.2
RFToolsPower version: 5.0.0

_As [posted](https://discord.com/channels/403871125206990849/403872061568712705/1005180909399584868) on Discord,_
RFToolsPower's power cells, when mined, drop empty rather than whatever energy level they have in them.
![Untitled](https://user-images.githubusercontent.com/84727791/184432814-68ea0611-8577-48cd-bb6b-3c5134b579c4.png)
![Untitled2](https://user-images.githubusercontent.com/84727791/184432832-5721eccf-2569-4ec9-9892-2a13d627b594.png)

Perhaps this is related to #66 ?

Other mods in the instance:

- Curios API 5.1.1.0
- Cyclic 1.7.8
- Initially 1.1.1
- Inventory Profiles Next 1.6.3
- Jade 8.1.0
- Just Enough Items 11.2.0.246
- KotlinForForge 3.7.1
- NoTelemetry 1.4.0
- OreExcavation 1.11.165 (not used)
- Patchouli 1.19-75
- RFToolsStorage 4.0.0
- RFToolsUtility 5.0.0
- Tool Belt 1.19.6
- XNet 5.0.1

**Comment by McJty** [comment]
Fixed in 1.18 and 1.19
