### ISSUE TITLE
Endergenic generator render issues

### ISSUE THREAD

**Issue by MCChiter** [McJtyMods/RFToolsPower#89]
Observed in Enigmatica 8 modpack v2.1.0

Unlike all tutorials on how to use it, there is no rendered properties of the machine, you can't set the screen to show when did the pearl arrive, there is no animation of the generator pulsing, which makes setup this much harder. The ingame manual from RFT base doesn't update to tell you anything on how it works and no matter how i try, a pretty cool powergen just denies me the ability to use it proper on the server because setting ticks correctly seems near impossible having to squat at each block and see where things went wrong this time around

To make the problem clearer, since i was lazy, i am trying to replicate this setup https://www.youtube.com/watch?v=9XvbHc18EJc and i see how is it supposed to work at least on the primary set of sequencers, yet as soon as i set the last sequencer everything breaks and the pearl arrives at the first endergenic while it's idle. i really hope it becomes a more reliable source of RF generation that works at least in it's basis because currently it really is dancing with a tambourine in the first moon of senile dragon in a rainstorm in a bamboo forest and summoning buddha to materialize as Saitama and give you an infinity stone levels of setting up.

Edit: #80

**Comment by Kangy1103** [comment]
I'm also seeing this (or not seeing as the case may be) on 1.18.2 on rftoolspower-1.18-4.0.7. Happy to open my own bug report if needed. Just let me know :)

**Comment by McJty** [comment]
Busy fixing this

**Comment by McJty** [comment]
Fixed
